# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Platformer iOS' do
pod 'Firebase', '>= 2.2.0'
pod 'Mixpanel'
end

target 'Platformer Android' do
pod 'Mixpanel'
end

target 'Platformer Mac' do

end

